---
output: github_document
bibliography: references.bib
---

# Motivation and Purpose

**Our role**: Data Science team at VanRealtor

**Target audience**: Real estate customers looking to buy properties in Vancouver neighbourhoods and Real estate agents at Realtor looking for listings in safer neighbourhoods to attract more clients.  

Being the largest city in British Columbia, Vancouver is an attractive city to call home for many. Reasons include its vast ethnic diversity, natural landscape, coastal, foresty, job market and so on. Despite the vibrant qualtiies of this city, an important factor when deciding to live in a specific city depends on the safety of its neighbourhoods, along with other factors such as access to essential services, cost of living etc. Research evidence have shown that crime types have had significant changes during COVID at neighbourhood levels in Vancouver [@vancrime]. For example, assault cases, aroson and robbery have increased in Vancouver's Downtown core, stratchcona and Mount Pleasant areas. At VanRealtor, we wanted to offer our clients the decision to choose their next neighbourhood to move, rent or visit while being aware of the crimes statistics of the city. This dashboard allows people to search for crime related information by neighbourhoods in Vancouver using data from 2021. Users can filter data based on geological location, monthly crime rates, crime types and  ..(will update as we finalize)

# Data Description
















# Research Questions and Usage Scenarios













# Description of app and dashboard sketch










# References